# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f69d7847d0029c4e9c73f6d55ac27f4ab3a7061285dcde2f64f5c9e9d0d6bb16f70155b147018828ebb49198ce43b396c3a9bfaeb7fab7890f208f11d555bc

test:
  secret_key_base: c264b6c9152ae0afc2262966668569ce65df00a8887589b199574e47b6fb508e091846ef84f40d00c5257969514e529b145e4bb04667cbcc083512321f3b8bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
